export interface DefiTerm {
  id: string;
  label: string;
  definition: string;
  stellarContext?: string;
  tooltip?: string;
}

export const defiTerms: Record<string, DefiTerm> = {
  trustlines: {
    id: 'trustlines',
    label: 'Trustlines',
    definition:
      'A trustline is a relationship you establish on the Stellar network to hold a specific asset. It represents your willingness to accept and trade that asset.',
    stellarContext:
      'On Stellar, you must create a trustline before you can receive or hold any token other than the native XLM. Each trustline has a configurable limit and requires a small XLM reserve. In Harvest Finance, trustlines are automatically managed when you interact with vaults.',
    tooltip: 'A Stellar trustline lets you hold non-XLM tokens. Harvest Finance manages them automatically when you use vaults.',
  },
  shares: {
    id: 'shares',
    label: 'Shares',
    definition:
      'Shares represent your proportional ownership stake in a vault. When you deposit assets, you receive shares; when you withdraw, you redeem shares for the underlying assets.',
    stellarContext:
      'In Harvest Finance vaults on Stellar, shares are tracked using Soroban i128 integers for precision. The number of shares you receive depends on the current vault ratio (totalAssets / totalShares) at deposit time. As the vault earns yield, the value of each share increases.',
    tooltip: 'Shares represent your vault ownership. Their value grows as the vault earns yield through Stellar strategies.',
  },
  slippage: {
    id: 'slippage',
    label: 'Slippage',
    definition:
      'Slippage is the difference between the expected price of a trade and the actual executed price. It occurs when market conditions change between order submission and execution.',
    stellarContext:
      'On Stellar, slippage is controlled by the minReceive parameter in path payment operations. When Harvest Finance executes swaps or rebalances, it sets a slippage tolerance to protect against unfavorable price movements. Higher slippage tolerance increases the chance of transaction success but may result in worse rates.',
    tooltip: 'Slippage is the difference between expected and actual trade price. Stellar uses minReceive to limit it.',
  },
  apy: {
    id: 'apy',
    label: 'APY',
    definition:
      'Annual Percentage Yield (APY) is the real rate of return on an investment, accounting for the effect of compounding interest over a year.',
    stellarContext:
      'Harvest Finance calculates APY based on historical yield data from Stellar vault contracts. The 7-day rolling APY smooths out short-term volatility to give a more reliable estimate of expected returns.',
    tooltip: 'APY is your annual return with compounding. Harvest uses a 7-day rolling average for accuracy.',
  },
  tvl: {
    id: 'tvl',
    label: 'TVL',
    definition:
      'Total Value Locked (TVL) represents the total amount of assets deposited in a vault or protocol. It is a key metric for measuring protocol health and liquidity.',
    tooltip: 'TVL is the total assets deposited in a vault. Higher TVL means more liquidity and stability.',
  },
  vault: {
    id: 'vault',
    label: 'Vault',
    definition:
      'A vault is a smart contract that pools user deposits and automatically deploys them into yield-generating strategies. Users receive shares proportional to their contribution.',
    stellarContext:
      'Harvest Finance vaults run on the Stellar network using Soroban smart contracts. Each vault implements a specific agricultural-themed yield strategy and tracks deposits/withdrawals using i128 precision integers.',
    tooltip: 'A vault pools deposits and runs yield strategies on Stellar via Soroban smart contracts.',
  },
  yield: {
    id: 'yield',
    label: 'Yield',
    definition:
      'Yield refers to the earnings generated by an investment over a specific period, typically expressed as a percentage of the invested amount.',
    stellarContext:
      'In Harvest Finance, yield is generated through Stellar DeFi strategies like lending, liquidity provision, and staking. Crop cycles simulate seasonal yield patterns unique to the platform.',
    tooltip: 'Yield is your investment earnings over time, generated through Stellar DeFi strategies.',
  },
  'price_per_share': {
    id: 'price_per_share',
    label: 'Price per Share',
    definition:
      'The price per share represents the underlying asset value of a single vault share. It is calculated as totalAssets / totalShares.',
    stellarContext:
      'On Stellar vaults, the price per share increases as yield is harvested and compounded. This metric helps you understand how much your shares are worth in underlying assets.',
    tooltip: 'The asset value of one share. It grows as yield is harvested and compounded.',
  },
  'risk_level': {
    id: 'risk_level',
    label: 'Risk Level',
    definition:
      'Risk level indicates the potential for loss in a vault strategy. Lower risk means more stable returns, while higher risk offers greater potential yields with increased volatility.',
    tooltip: 'Indicates potential for loss. Lower risk = stable returns, higher risk = more volatile but potentially higher yields.',
  },
  strategy: {
    id: 'strategy',
    label: 'Strategy',
    definition:
      'A strategy defines how a vault deploys deposited assets to generate yield. Different strategies carry different risk-return profiles.',
    stellarContext:
      'Harvest Finance strategies on Stellar include lending protocols, liquidity pools, and staking mechanisms. Each strategy is optimized for the agricultural-themed yield cycles.',
    tooltip: 'How a vault generates yield — e.g., lending, liquidity pools, or staking on Stellar.',
  },
};

export function getTermTooltip(termId: string): string {
  const term = defiTerms[termId];
  if (!term) return '';
  return term.tooltip || term.stellarContext || term.definition;
}

export function getTermLabel(termId: string): string {
  return defiTerms[termId]?.label || termId;
}
